image: docker:latest

stages:
  - build
  - push

Build:
  stage: build
  script:   
    - docker pull docker-registry.ebrains.eu/nest/nest-simulator:dev
    - docker build 
        --cache-from docker-registry.ebrains.eu/nest/nest-simulator:dev
        --tag docker-registry.ebrains.eu/nest/nest-simulator:dev.$CI_PIPELINE_ID 
        ./src/dev
