version: "3"

services:
  nest-server:
    image: nestsim/nest:3.4
    environment:
      LOCAL_USER_ID: "`id -u $USER`"
      NEST_CONTAINER_MODE: "nest-server"
    ports:
      - "5000:5000"

  nest-desktop:
    image: nestsim/nest:3.4
    environment:
      LOCAL_USER_ID: "`id -u $USER`"
      NEST_CONTAINER_MODE: "nest-desktop"
    ports:
      - "8000:8000"
    depends_on:
      - nest-server

  nest-notebook:
    image: nestsim/nest:3.4
    volumes:
      - .:/opt/data
    environment:
      LOCAL_USER_ID: "`id -u $USER`"
      NEST_CONTAINER_MODE: "notebook"
    ports:
      - "8080:8080"

  nest-jupyterlab:
    image: nestsim/nest:3.4
    volumes:
      - .:/opt/data
    environment:
      LOCAL_USER_ID: "`id -u $USER`"
      NEST_CONTAINER_MODE: "jupyterlab"
    ports:
      - "8080:8080"
