services:
  nest-server:
    image: docker-registry.ebrains.eu/nest/nest-simulator:latest
    environment:
      - LOCAL_USER_ID=`id -u $USER`
    ports:
      - "5000:5000"
    command:
      - nest-server

  nest-desktop:
    image: docker-registry.ebrains.eu/nest/nest-simulator:latest
    environment:
      - LOCAL_USER_ID=`id -u $USER`
    ports:
      - "8000:8000"
    command:
      - nest-desktop
    depends_on:
      - nest-server

  nest-notebook:
    image: docker-registry.ebrains.eu/nest/nest-simulator:latest
    volumes:
      - .:/opt/data
    environment:
      - LOCAL_USER_ID=`id -u $USER`
    ports:
      - "8080:8080"
    command:
      - notebook

  nest-jupyterlab:
    image: docker-registry.ebrains.eu/nest/nest-simulator:latest
    volumes:
      - .:/opt/data
    environment:
      - LOCAL_USER_ID=`id -u $USER`
    ports:
      - "8080:8080"
    command:
      - jupyterlab