###############################################
###               v3.6                     ###
###############################################

Build_36:
  stage: build
  needs: ["Build_Base"]
  script:
    - docker pull nest/nest-simulator:3.6 || true
    - docker build
        --cache-from nest/nest-simulator:3.6
        --tag $DOCKER_REGISTRY_IMAGE:3.6.$CI_PIPELINE_ID
        ./src/3.6
    # Simple test
    - docker run -i --rm nest/nest-simulator:3.6 bash /opt/test-nest.sh
  tags:
    - shell-runner

Deploy_36:
  stage: deploy
  needs: ["Build_36"]
  when: never
  script:    
    - echo -n $DOCKERHUB_REGISTRY_TOKEN | docker login -u $DOCKERHUB_REGISTRY_USER --password-stdin
    - docker push nest/nest-simulator:3.6
    - docker logout $DOCKERHUB_REGISTRY
  only:
    - master
  tags:
    - shell-runner
