###############################################
###               v3.0                      ###
###############################################

Build_30:
  stage: build
  needs: ["Build_Base"]
  variables:
    DORUN: "false"
  rules:
    - if: $DORUN== "false"
      when: never
    - when: manual
    - allow_failure: true
  script:
    - docker pull $DOCKER_REGISTRY_IMAGE:3.0  || true
    - docker build 
        --cache-from $DOCKER_REGISTRY_IMAGE:3.0
        --tag $DOCKER_REGISTRY_IMAGE:3.0.$CI_PIPELINE_ID 
        ./src/3.0
    - docker push $DOCKER_REGISTRY_IMAGE:3.0.$CI_PIPELINE_ID
  tags:
    - shell-runner

Test_30:
  stage: test
  needs: ["Build_30"]
  variables:
    DORUN: "false"
  rules:
    - if: $DORUN== "false"
      when: never
    - when: manual
    - allow_failure: true
  script:
    - docker pull $DOCKER_REGISTRY_IMAGE:3.0.$CI_PIPELINE_ID
    - docker stop $(docker ps -q) 2>/dev/null || true
    - docker rm -f $(docker ps -aq) 2>/dev/null || true
    - docker ps
    - docker run -i -d --rm -e NEST_CONTAINER_MODE=nest-server -p 5000:5000  
        --name $CI_PIPELINE_ID $DOCKER_REGISTRY_IMAGE:3.0.$CI_PIPELINE_ID
    - docker ps
  tags:
    - shell-runner

Deploy_30:
  stage: deploy
  needs: ["Test_30"]
  variables:
    DORUN: "false"
  rules:
    - if: $DORUN== "false"
      when: never
    - when: manual
    - allow_failure: true
  script:
    - docker pull $DOCKER_REGISTRY_IMAGE:3.0.$CI_PIPELINE_ID
    - docker tag $DOCKER_REGISTRY_IMAGE:3.0.$CI_PIPELINE_ID $DOCKER_REGISTRY_IMAGE:3.0
    - docker push $DOCKER_REGISTRY_IMAGE:3.0
    - echo -n $DOCKERHUB_REGISTRY_TOKEN | docker login -u $DOCKERHUB_REGISTRY_USER --password-stdin
    - docker tag $DOCKER_REGISTRY_IMAGE:3.0 nest/nest-simulator:3.0
    - docker push nest/nest-simulator:3.0
    - docker logout $DOCKERHUB_REGISTRY
  tags:
    - shell-runner
