###############################################
###               v3.1                      ###
###############################################

Build_31:
  stage: build
  needs: ["Build_Base"]
  rules:
   - when: never
  script:
    - docker pull $DOCKER_REGISTRY_IMAGE:3.1  || true
    - docker build 
        --cache-from $DOCKER_REGISTRY_IMAGE:3.1
        --tag $DOCKER_REGISTRY_IMAGE:3.1.$CI_PIPELINE_ID 
        ./src/3.1
    - docker push $DOCKER_REGISTRY_IMAGE:3.1.$CI_PIPELINE_ID
  tags:
    - shell-runner

Test_31:
  stage: test
  needs: ["Build_31"]
  rules:
   - when: never
  script:
    - docker pull $DOCKER_REGISTRY_IMAGE:3.1.$CI_PIPELINE_ID
    - docker stop $(docker ps -q) 2>/dev/null || true
    - docker rm -f $(docker ps -aq) 2>/dev/null || true
    - docker ps
    - docker run -i -d --rm -e NEST_CONTAINER_MODE=nest-server -p 5000:5000  
        --name $CI_PIPELINE_ID $DOCKER_REGISTRY_IMAGE:3.1.$CI_PIPELINE_ID
    - docker ps
  tags:
    - shell-runner

Deploy_31:
  stage: deploy
  needs: ["Test_31"]
  rules:
   - when: never
  script:
    - docker pull $DOCKER_REGISTRY_IMAGE:3.1.$CI_PIPELINE_ID
    - docker tag $DOCKER_REGISTRY_IMAGE:3.1.$CI_PIPELINE_ID $DOCKER_REGISTRY_IMAGE:3.1
    - docker push $DOCKER_REGISTRY_IMAGE:3.1
    - echo -n $DOCKERHUB_REGISTRY_TOKEN | docker login -u $DOCKERHUB_REGISTRY_USER --password-stdin
    - docker tag $DOCKER_REGISTRY_IMAGE:3.1 nest/nest-simulator:3.1
    - docker push nest/nest-simulator:3.1
    - docker logout $DOCKERHUB_REGISTRY
  tags:
    - shell-runner
